branches:
  only:
    - appveyor-test
skip_tags: true

environment:
  matrix:
    # electron
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 1.6.3
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF

artifacts:
  - path: '**\electron-*.tar.gz'
    name: binary-package
