branches:
  only:
    - appveyor-test
skip_tags: true

environment:
  matrix:
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
      TOOLSET_ARGS: --runtime=electron --target=1.6.0 --dist-url=https://atom.io/download/electron

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF

artifacts:
  - path: '**\electron-*.tar.gz'
    name: binary-package
